name: GitHub Crawler

on:
  workflow_dispatch:  # run manually from Actions tab
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set timeout to prevent infinite runs

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          for i in `seq 1 30`; do
            pg_isready -h localhost -p 5432 -U postgres && exit 0
            sleep 2
          done
          exit 1
        env:
          PGPASSWORD: postgres

      - name: Create schema
        run: psql -h localhost -U postgres -d postgres -f schema.sql
        env:
          PGPASSWORD: postgres

      - name: Run crawler
        run: python crawler.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump DB to CSV
        run: |
          psql -h localhost -U postgres -d postgres -c "\COPY repositories TO 'repos.csv' CSV HEADER"
          ls -lah
        env:
          PGPASSWORD: postgres

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: repos-data
          path: repos.csv