name: GitHub Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: write   # ✅ allow pushing changes

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ use built-in token
          fetch-depth: 0                       # needed for commits

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python crawler.py

      - name: Commit repos.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # only commit if repos.csv changed
          git add repos.csv
          if git diff --cached --quiet; then
            echo "No changes in repos.csv, skipping commit"
            exit 0
          fi

          git commit -m "chore: update repos.csv [skip ci]"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
