name: GitHub Crawler

on:
  workflow_dispatch:  # allow manual trigger
  schedule:
    - cron: "0 12 * * 1"  # run every Monday at 12:00 UTC

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run crawler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python crawler.py

      - name: Commit repos.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repos.csv
          git commit -m "chore: update repos.csv [skip ci]" || echo "No changes to commit"
          git push
