name: GitHub Crawler

on:
  workflow_dispatch:   # run manually
  schedule:
    - cron: "0 6 * * 1"   # run every Monday at 06:00 UTC

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 🔑 uses GitHub’s built-in token
        run: |
          python crawler.py

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: learning_repos
          path: learning_repos.csv

      - name: Commit & push CSV to repo
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add learning_repos.csv
          git commit -m "Update learning_repos.csv [skip ci]" || echo "No changes to commit"
          git push
